config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"


  devise_for :users
  resources :posts

  get 'welcome/homepage'
  root 'welcome#homepage'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# before_action :set_post, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
def index
  @posts = Post.all
end

def show
  @post = Post.find(params[:id])
end

def new
  @post = current_user.posts.build
  #@post = Post.new
end
#leave new empty if it doesnt work


def edit
  @post = Post.find(params[:id])
end

  def create
    # render plain: params[:post].inspect
  @post = current_user.posts.build(post_params)

    @post.save
    redirect_to @post
  end

def update
  @post = Post.find(params[:id])
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

private
def post_params
  params.require(:post).permit(:title, :text)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Collective Action">
<meta name="application-name" content="Collective Action">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffd600">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help Our Humans</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="//cdn.ckeditor.com/4.6.1/standard/ckeditor.js"></script>

    <%= render 'application/favicon' %>
  </head>

  <body>
    <div class = "navbar">
        <ul class="myMenu">
          <li><img class="logo" src="<%= asset_path( 'CA-logo.png' ) %>" /></li>
          <li><%= link_to 'Help Our Humans', welcome_homepage_path %></li>
          <li><%=link_to 'Learn More', posts_path%></li>
          <li><a href="http://localhost:3000/pages/donate">Donate</a></li>
        </ul>

        <ul class="userLinks">
          <% if user_signed_in? %>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to('Login', new_user_session_path)  %></li>
          <% end %>
        </ul>
    </div>

  <!-- <footer class="footer">
    <div class="contactLinks">
    <%= link_to "Twitter", "http://twitter.com", :target => "_blank" %>
    <%= link_to "Facebook", "http://facebook.com", :target => "_blank" %>
  </div>
  </footer> -->

  <%= yield %>
  <!-- <script src="/Users/Diana/desktop/wdi/projects/organization/app/assets/javascripts/application.js"></script> -->
  </body>
</html>

app/views/pages/donate.html.erb
<h1> How You Can Help </h1>
<div class="donate">
  <div class="donateSection">
    <div id="page">
      <p>Here is a list of great organization making an effort to help the cause. If you are interested in donating or finding ways to participate, please view these pages.</p>
      <a href="http://irusa.org/refugee-crisis/?gclid=CjwKEAjwxurIBRDnt7P7rODiq0USJADwjt5D4n58j7y-UAKIufa8R5aZy__r8eth1zvTtKLc17nZ4BoCI2Hw_wcB">Islamic Relief USA</a>
      <br>
      <a href="https://donate.worldvision.org/world-vision-refugee-initiative/?campaign=119351403&gclid=CjwKEAjwxurIBRDnt7P7rODiq0USJADwjt5Dte5_T7yuL1yN_bj2KHguPnxj6hN7PeEqspHF_N4GahoCPu_w_wcB">World Vision</a>
      <br>
      <a href="https://www.crowdrise.com/donate/project/savethechildrenrefug/savethechildren/?widget=true&huffpo=true">Save the Children</a>
      <br>
      <a href="https://donate.doctorswithoutborders.org/onetime.cfm?utm_expid=7773760-9.T4pemk1yTFeOymrJr_YtIQ.0&utm_referrer=http%3A%2F%2Fwww.doctorswithoutborders.org%2Fnews-stories%2Fsyria-filling-gaps-and-providing-care-aleppo-governorate">Doctors Without Borders</a>
      <br>
      <a href="https://peoplesmillion.whitehelmets.org/donate/peoples-million">The White Helmits</a>
      <br>
      <a href="http://www.unrefugees.org/?_ga=2.158723386.1026033860.1494948548-507849225.1494948545">UNHCR</a>
      <br>
      <a href="https://www.unicefusa.org/mission/emergencies/child-refugees/syria-crisis?utm_campaign=2017_misc&utm_medium=cpc&utm_source=20171122_cpc&utm_content=Syria_aleppo&ms=cpc_dig_2017_misc_20171122_Google_Syria_Aleppo&initialms=cpc_dig_2017_misc_20171122_Google_Syria_Aleppo">unicef USA</a>

    </div>

  </div>
  <div class="payPal">To help refugees, you need to understand where they are located and what organizations are addressing their needs on the ground. If you are willing to be more strategic with your dollar, it will go a lot further. </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts & Announcements</h1>

<%= link_to 'New Post', new_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>User</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= post.user.email %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <% if post.user == current_user %>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post,
            method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>Announcement || New Campaign</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2></h2>
<h2 class="postTitle">
  <strong>Title:</strong>
  <%= @post.title %>
</h2>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

app/views/welcome/homepage.html.erb
<div class="homePage">
  <img class="coverPic" src="<%= asset_path( 'refugees1.jpg' ) %>" />
  <img class="logoPic" src="<%= asset_path( 'CA-logo2.png' ) %>" />
</div>

<div class="tagline"></div>
<div class="tag">"Join us in our fight for humanity."</div>

<div class="sectionLine"><div>
<div class="section">
  <div class="liveFeed">
    <h1 class="smsHeader">H E A R  ·  U S</h1>
    <div class="texts">
    </div>
  </div>

  <div class="aboutSection">
    <h1> Our Mission </h1>
    <p class="mission">Organizations work around the world to protect refugees who have been forced to flee their homelands because of who they are, including ethnic, religious, and sexual minorities. Their mission is to help refugees rebuild their lives in safety and dignity.</p>


    <h2> What We Do </h2>
    <p>
    Our Page: <br>
    <span class="gray">Advocates for widespread policy changes</span> within agencies, organizations, and governing bodies to benefit the greatest possible number of vulnerable refugees.<br>
    <span class="gray">Forms and participates in strategic coalitions</span> with other refugee rights advocacy organizations, human rights groups, legal aid centers, non-governmental organizations,  and faith-based organizations to increase awareness or collaborations to further certain agendas in the protection of vulnerable refugees.<br>
    <span class="gray">Provides a resource database for refugees themselves</span> to assist them from the time they leave home, until they are safely resettled in supportive communities.
  </p>
        <%= link_to 'Get information on how you can help here', controller: 'posts' %>
  </div>
</div>